name: POC

on:
    workflow_dispatch:
        inputs:
            PROJECT_KEY:
                description: "SonarQube Project Key"
                required: true
                type: string
            TRIGGER_NEW_SCAN:
                description: "Trigger a new SonarQube scan (true/false)"
                required: true
                type: boolean

jobs:
    sonarqube-scan:
        name: sonarqube-scan
        runs-on: ubuntu-latest
        if: ${{ inputs.TRIGGER_NEW_SCAN == 'true' }}
        env:
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for better analysis
                  submodules: true # Ensure submodules are also checked out

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              with:
                  projectBaseDir: ${{ inputs.PROJECT_KEY }}
                  args: >
                      -Dsonar.projectKey=${{ inputs.PROJECT_KEY }}

    filter-fp-dry-run:
        name: filter-fp-dry-run
        runs-on: ubuntu-latest
        if: always()
        needs: sonarqube-scan
        env:
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for better analysis

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14"

            - run: pip install requests asyncio github-copilot-sdk

            - name: Filter False Positives (Dry Run)
              run: python3 filter_fp.py --project_key ${{ inputs.PROJECT_KEY }}

    filter-fp:
        name: filter-fp
        runs-on: ubuntu-latest
        if: always()
        needs: filter-fp-dry-run
        environment: manual-approval
        env:
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14"

            - run: pip install requests asyncio github-copilot-sdk

            - name: Filter False Positives
              run: python3 filter_fp.py --project_key ${{ inputs.PROJECT_KEY }} --apply
